### PR TITLE
PLT1395: fix and update sdk-php

### PR DESCRIPTION
**Pull request by sibinlu**

### CODE REVIEW

**Review by javidang — APPROVED** [review]
I guess these php changes are from proto compiler, and can be ingored?

**Comment by sibinlu** [comment]
@javidang it is from our build script, you can review the first commit only since it is fixing tests with business logic

**Comment by javidang** [comment]
@sibinlu , yeap, I only checked the first commit.

**Comment by marcomarsala** [comment]
upgrading to version 2.0.7 with composer, nothing works anymore. I suspect some dependencies update broke things. downgrading to 2.0.6 works again

**Pull request merged**
